Repository Nexters/www-be, pull requests merged in 2023-02, with the labels that each got.

#32 [Nexters/www-be#6] Add getMeeting api
  src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
  src/main/java/com/promise8/wwwbe/model/dto/PlatformType.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseDateAndTimeDto.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseDateAndTimeReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/UserVoteResDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingUserRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingUserTimetableRepository.java
  src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: feature

#38 [nexters/www-be#noissue] push test용 controller 추가
  src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
  src/main/java/com/promise8/wwwbe/config/security/UserPrincipal.java
  src/main/java/com/promise8/wwwbe/controller/PushTestController.java
  src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
  src/main/java/com/promise8/wwwbe/service/PushService.java
  src/test/java/com/promise8/wwwbe/service/IntegrationPushServiceTest.java
  src/test/java/com/promise8/wwwbe/service/PushServiceTest.java
Labels: feature, test

#37 [Nexters/www-be#35] Add authorization in swagger
  src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
  src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
  src/main/java/com/promise8/wwwbe/config/security/TokenAuthenticationFilter.java
Labels: setup

#36 [Nexters/www-be#34] Fix Entities
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingStatus.java
  src/main/java/com/promise8/wwwbe/model/dto/UserVoteResDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: fix

#41 [nexters/www-be#40] 방장 액션으로 방 상태 수정
  src/main/java/com/promise8/wwwbe/config/WebConfig.java
  src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
  src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/converter/MeetingStatusConverter.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingStatus.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java
  src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
Labels: feature

#43 [Nexters/www-be#6] Add getMeetingList
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java
Labels: feature

#46 [Nexters/www-be#6] Fix Enum compare
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
Labels: fix

#47 [Nexters/www-be#6] Add sort Meeting
  src/main/java/com/promise8/wwwbe/config/ObjectMapperConfig.java
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/ConfirmedPromiseDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseDayOfWeek.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
Labels: feature

#53 [Nexters/www-be#50] Add isHost, dynamicLink
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: feature

#54 [Nexters/www-be#51] Add priority in enums
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java
Labels: fix

#59 [Nexters/www-be#noissue] Add MeetingServiceTest
  pom.xml
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/ConfirmedPromiseDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
Labels: fix, test

#60 [Nexters/www-be#noissue] Fix update userName at create meeting
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: fix

#57 [Nexters/www-be#56] Add Scheduler for change MeetingStatus
  src/main/java/com/promise8/wwwbe/WwwBeApplication.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: feature

#55 [nexters/www-be#9] vote place list
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/PlaceVoteReqDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingUserRepository.java
  src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: feature

#61 [Nexters/www-be#noissue] Add meetingRepo test
  src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java
Labels: test

#64 [Nexters/www-be#63] Add checking isJoined user and meetingStatus
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
Labels: fix

#67 [Nexters/www-be#66] Fix Swagger Request url
  src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
Labels: fix

#69 [Nexters/www-be#68] Fix Swagger host
  src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
Labels: fix

#71 [Nexters/www-be#48] Add nullable responsedto
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java
Labels: docs, refact

#74 [Nexters/www-be#73] Add api description for swagger
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/UserController.java
  src/main/java/com/promise8/wwwbe/service/UserService.java
Labels: docs

#78 [Nexters/www-be#77] Fix isConfirmed at createMeeting
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: fix

#79 [Nexters/www-be#76] Refactoring sorting
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDtoWrapper.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: refact

#80 [Nexters/www-be#77] Add votingUserCount in MeetingDetail
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
Labels: fix

#81 [Nexters/www-be#77] Add solving conflict of place
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: fix

#82 [Nexters/www-be#77] Add currentUserName and Fix userName at join
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
Labels: fix

#84 [Nexters/www-be#83] Add Dockerfile and cicd.yml for cicd
  .github/workflows/cicd.yml
  infra/Dockerfile
Labels: Infra, actions

#86 [Nexters/www-be#83] Fix path
  .github/workflows/cicd.yml
Labels: Infra, actions, fix

#87 Merge develop to master
  .github/workflows/cicd.yml
Labels: Infra, actions, fix

#88 [Nexters/www-be#83] Fix Dockerfile
  infra/Dockerfile
Labels: Infra, fix

#89 Fix Dockerfile
  infra/Dockerfile
Labels: Infra, fix

#90 [Nexters/www-be#83] Fix cicd rmi
  .github/workflows/cicd.yml
Labels: Infra, fix

#91 [Nexters/www-be#83] Fix cicd
  .github/workflows/cicd.yml
Labels: Infra, fix

#94 [nexters/www-be#noissue] response add
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
Labels: fix

#96 [nexters/www-be#noissue] response add (#94)
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
Labels: fix

#97 [Nexters/www-be#77] Fix swagger docs
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/UserController.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: docs, fix

#98 [Nexters/www-be#77] Fix swagger docs (#97)
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/UserController.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: docs, fix

#100 [Nexters/www-be#77] Delete result at BaseResponse error
  src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: fix

#101 Fix BaseResponse and cicd
  .github/workflows/cicd.yml
  src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
  src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: Infra, actions, fix

#102 [Nexters/www-be#77] Delete no use
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/exception/BizException.java
Labels: refact

#103 [Nexters/www-be#77] Add getTimetableList
  src/main/java/com/promise8/wwwbe/controller/MeetingUserTimetableController.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/MeetingUserTimetableService.java
Labels: feature

#106 [Nexters/www-be#noissue] Add push master notification
  .github/workflows/slack.yml
Labels: actions

#107 [Nexters/www-be#92] Add Notification by api
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java
  src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
  src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/test/java/com/promise8/wwwbe/repository/PlaceVoteRepositoryTest.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
  src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java
Labels: feature

#108 [Nexters/www-be#77] Add init isAlarmOn
  src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
Labels: fix

#110 [Nexters/www-be#93] Add notification scheduler
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingUserTimetableRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
Labels: feature

#111 [nexters/www-be#noissue] 약속 확정 API, 약속 확정 재촉 노티
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/req/MeetingConfirmDto.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java
Labels: feature

#112 master
  .github/workflows/slack.yml
  src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/MeetingUserTimetableController.java
  src/main/java/com/promise8/wwwbe/controller/PlaceVoteController.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
  src/main/java/com/promise8/wwwbe/model/dto/req/MeetingConfirmDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/PromisePlaceResDtoWrapper.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
  src/main/java/com/promise8/wwwbe/model/exception/BizException.java
  src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
  src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/repository/MeetingUserTimetableRepository.java
  src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/MeetingUserTimetableService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/test/java/com/promise8/wwwbe/repository/PlaceVoteRepositoryTest.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
  src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java
Labels: actions

#114 [nexters/www-be#noissue] refactoring chracter (#113)
  src/main/java/com/promise8/wwwbe/model/dto/UserInfoDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromiseTimeResDto.java
  src/main/java/com/promise8/wwwbe/service/LinkService.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java
Labels: actions

#115 [nexters/www-be#noissue] push message
  src/main/java/com/promise8/wwwbe/model/entity/PushMessageHistoryEntity.java
  src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
  src/main/java/com/promise8/wwwbe/repository/PushMessageHistoryRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/main/java/com/promise8/wwwbe/service/PushService.java
  src/test/java/com/promise8/wwwbe/service/IntegrationPushServiceTest.java
  src/test/java/com/promise8/wwwbe/service/PushServiceTest.java
Labels: fix

#116 [nexters/www-be#noissue] push message (#115)
  src/main/java/com/promise8/wwwbe/model/entity/PushMessageHistoryEntity.java
  src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
  src/main/java/com/promise8/wwwbe/repository/PushMessageHistoryRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/main/java/com/promise8/wwwbe/service/PushService.java
  src/test/java/com/promise8/wwwbe/service/IntegrationPushServiceTest.java
  src/test/java/com/promise8/wwwbe/service/PushServiceTest.java
Labels: actions

#117 [Nexters/www-be#77] Fix promiseTime naming
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
Labels: fix

#118 [Nexters/www-be#77] Fix bugs
  src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: fix

#119 fix some bugs
  src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: actions

#120 [Nexters/www-be#77] Fix CharacterType userId -> meetingUserId
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
Labels: bug

#122 [Nexters/www-be#77] Fix meetingDetail userName
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
Labels: bug

#123 [Nexters/www-be#77] Fix CharacterType host
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java
Labels: fix

#124 [Nexters/www-be#77] Fix pushMsgHistoryId
  src/main/java/com/promise8/wwwbe/service/PushService.java
Labels: fix

#125 Fix Character and pushMessageHistory
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/PushService.java
  src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java
Labels: fix

#126 [Nexters/www-be#77] Add vote method
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/res/UserPromiseTimeResDto.java
  src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
Labels: fix

#127 [Nexters/www-be#77] delete calling notification
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
  src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
Labels: fix
