Repository Nexters/www-be, pull requests merged in 2023-01, with the labels that each got.

#16 [Nexters/www-be#13] Fix project setup in controller
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/controller/UserController.java
Labels: setup

#18 [Nexters/www-be#17] Add created and updated datetime
  src/main/java/com/promise8/wwwbe/WwwBeApplication.java
  src/main/java/com/promise8/wwwbe/model/entity/BaseTimeEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
Labels: setup

#15 [Nexters/www-be#14] Add Maven build test
  .github/workflows/maven.yml
  src/test/java/com/promise8/wwwbe/repository/UserRepositoryTest.java
Labels: actions

#23 [Nexters/www-be#22] Add slack and github connect
  .github/workflows/slack.yml
Labels: setup

#24 [Nexters/www-be#20] Fix Entities
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
Labels: setup

#25 [Nexters/www-be#21] Fix branch name to applying workflows
  .github/workflows/maven.yml
  .github/workflows/slack.yml
Labels: actions

#26 [Nexters/www-be#20] Delete uuid in userEntity
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
Labels: setup

#28 [Nexters/www-be#11] firebase push notification 적용
  pom.xml
  src/main/java/com/promise8/wwwbe/config/FirebaseConfig.java
  src/main/java/com/promise8/wwwbe/config/FirebaseProperties.java
  src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
  src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
  src/main/java/com/promise8/wwwbe/controller/UserController.java
  src/main/java/com/promise8/wwwbe/model/dto/LoginReqDto.java
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
  src/main/java/com/promise8/wwwbe/model/exception/BizException.java
  src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
  src/main/java/com/promise8/wwwbe/model/http/BaseResponse.java
  src/main/java/com/promise8/wwwbe/service/PushService.java
  src/main/resources/application.yml
  src/main/resources/firebase-service-account.json
  src/test/java/com/promise8/wwwbe/service/PushServiceTest.java
Labels: feature

#29 [Nexters/www-be#6] Add createMeeting api
  pom.xml
  src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
  src/main/java/com/promise8/wwwbe/controller/MeetingController.java
  src/main/java/com/promise8/wwwbe/model/dto/DynamicLinkReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateResDto.java
  src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseDateAndTimeDto.java
  src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
  src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
  src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
  src/main/java/com/promise8/wwwbe/service/MeetingService.java
  src/main/resources/application-alpha.yml
  src/main/resources/application-local.yml
Labels: feature
